### ISSUE TITLE
Hangs on large files

### ISSUE THREAD

**Issue by anson-vandoren** [aaronwhittier/cribl#15]
I requested all lines from a large (~1.5GB) file. I left the curl request running for >10min before killing it with no results returned. I would expect a file of this size to be able to be returned in < 1 minute, which seems reasonable given that 3 million lines (vs ~15 million for the full file) are returned in ~15 seconds.

Note: running in a Docker container w/ the instructions provided in CONTRIBUTING.md file

**Comment by anson-vandoren** [comment]
Interestingly, if I use a smaller number of lines (e.g., 100), but use a search term that is not present in the file, the query correctly returns 0 lines, even though it also must iterate through the entire file to find that there is no match. So I'm guessing this issue is less about the reading and more about constructing a very large response

**Comment by aaronwhittier** [comment]
Yeah, I've never attempted to ask .NET to give me a response that large before, I will investigate.
